### ISSUE TITLE
Broken nwn-erf --extract on Windows

### ISSUE THREAD

**Issue by jakkn** [niv/nwn-lib#9]
Running `nwn-erf --extract -f module.mod` on Windows produces the below error

```
C:/Ruby23/lib/ruby/gems/2.3.0/gems/nwn-lib-0.6.1/lib/nwn/erf.rb:40:in
 'add': Invalid filename: ".res" (ArgumentError)
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/nwn-lib-0.6.1/lib/nwn/erf.rb:120:in 'block in read_from'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/nwn-lib-0.6.1/lib/nwn/erf.rb:115:in 'each'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/nwn-lib-0.6.1/lib/nwn/erf.rb:115:in 'each_slice'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/nwn-lib-0.6.1/lib/nwn/erf.rb:115:in 'read_from'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/nwn-lib-0.6.1/lib/nwn/erf.rb:28:in 'initialize'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/nwn-lib-0.6.1/bin/nwn-erf:143:in 'new'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/nwn-lib-0.6.1/bin/nwn-erf:143:in 'block in <top (required)>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/nwn-lib-0.6.1/bin/nwn-erf:111:in 'block in input'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/nwn-lib-0.6.1/bin/nwn-erf:111:in 'open'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/nwn-lib-0.6.1/bin/nwn-erf:111:in 'input'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/nwn-lib-0.6.1/bin/nwn-erf:142:in '<top (required)>'
        from C:/Ruby23/bin/nwn-erf:23:in 'load'
        from C:/Ruby23/bin/nwn-erf:23:in '<main>'
```

Temporarily fixed by rolling back to v0.6.0

**Comment by niv** [comment]
That looks like the module contains a file named ".res". That's strictly speaking not a valid resref (empty). How did that even happen? :)

**Comment by jakkn** [comment]
That is a good question :) Turns out this was due to a bug on my end where MD5 hashes were not generated correctly for the gff binaries on Windows, which led to the bad resources.

**Comment by niv** [comment]
Ah, fair enough.

I think that 0.6.0 allowed packing invalid resrefs. Checks I added in the new release now error out, so suppose that's what you are seeing here.
